language: go
go: 
- 1.1
- 1.2
- tip

script:
  - sudo add-apt-repository --yes ppa:chris-lea/node.js
  - sudo apt-get --yes update
  - sudo apt-get install --yes nodejs
  - npm install -g grunt-cli bower
  - npm install
  - bower install
  - grunt
  - go list -f '{{range .XTestImports}}{{.}}{{"\n"}}{{end}}' | xargs go get
  - go test ./...
