language: go
go: 
- 1.1
- 1.2
- tip

script:
  - npm install -g grunt-cli bower
  - npm install
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - bower install
  - grunt
  - go list -f '{{range .XTestImports}}{{.}}{{"\n"}}{{end}}' | xargs go get
  - go test ./...
